### ISSUE TITLE
Click `Click to show suggested questions` on the homepage to report an error

### ISSUE THREAD

**Issue by sunbod** [vanna-ai/vanna-streamlit#13]
Traceback (most recent call last):
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/home/sunbo/Documents/git/open_source/vanna-streamlit/app.py", line 41, in <module>
    questions = generate_questions_cached()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 168, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 197, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 224, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/streamlit/runtime/caching/cache_utils.py", line 280, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/Documents/git/open_source/vanna-streamlit/vanna_calls.py", line 14, in generate_questions_cached
    return vn.generate_questions()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/vanna/base/base.py", line 304, in generate_questions
    question_sql = self.get_similar_question_sql(question="", **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/vanna/lib/python3.11/site-packages/vanna/vannadb/vannadb_vector.py", line 383, in get_similar_question_sql
    return training_data.questions
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'questions'

**Comment by sunbod** [comment]
my python environment=3.11
