### ISSUE TITLE
Missing Feedback Questions

### ISSUE THREAD

**Issue by mparacha7** [vanna-ai/vanna-streamlit#14]
HI, 
The demo code for streamlit UI is not exhibiting the functionality as shown in demo gif, like after every output of SQL or plotly code , the user is asked if they are happy with it , presented with an option of yes or no. 

Also it will be very useful if we can retain the chat history . 

Thanks

**Comment by vnagireddy-symphonize** [comment]
I am having a similar issue.  The app is launching successfully.  But the moment I try to interact with it, I get messages similar to `AttributeError: 'NoneType' object has no attribute 'questions'` from within Vanna.  Any help is greatly appreciated.

**Comment by vnagireddy-symphonize** [comment]
> I am having a similar issue. The app is launching successfully. But the moment I try to interact with it, I get messages similar to `AttributeError: 'NoneType' object has no attribute 'questions'` from within Vanna. Any help is greatly appreciated.

Here is additional information about the issue that is being faced.

```bash
% streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://<IP_ADDRESS>:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog

2025-04-03 21:26:20.667 Uncaught app execution
Traceback (most recent call last):
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 640, in code_to_exec
    exec(code, module.__dict__)
  File "/<USER_PATH>/repos/<REPO_PATH>/app.py", line 41, in <module>
    questions = generate_questions_cached()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs, spinner_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 261, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<USER_PATH>/repos/<REPO_PATH>/vanna_calls.py", line 14, in generate_questions_cached
    return vn.generate_questions()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/vanna/base/base.py", line 331, in generate_questions
    question_sql = self.get_similar_question_sql(question="", **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<USER_PATH>/envs/<ENV_NAME>/lib/python3.12/site-packages/vanna/vannadb/vannadb_vector.py", line 383, in get_similar_question_sql
    return training_data.questions
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'questions'
```

**Comment by vnagireddy-symphonize** [comment]
> HI, The demo code for streamlit UI is not exhibiting the functionality as shown in demo gif, like after every output of SQL or plotly code , the user is asked if they are happy with it , presented with an option of yes or no.
> 
> Also it will be very useful if we can retain the chat history .
> 
> Thanks

@mparacha7 I know it's been a while, but, did you happen to get past this issue?
